spring.application.name=VentureBridge

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/venturebridge?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Alexbenva@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/,file:uploads/

venturebridge.upload-dir=uploads
venturebridge.public-base-url=/uploads

server.error.whitelabel.enabled=false
server.servlet.session.timeout=30m

logging.level.org.springframework.security=INFO