spring.jpa.hibernate.ddl-auto=validate
spring.thymeleaf.cache=true
server.error.whitelabel.enabled=false

venturebridge.upload-dir=/var/lib/venturebridge/uploads
venturebridge.public-base-url=/uploads